### ISSUE TITLE
Reaper scales layout every time it's recreated

### ISSUE THREAD

**Issue by nezvers** [iPlug2/iPlug2OOS#10] opened 2024-05-31 19:43 UTC
Windows 10 VST3
Reproduction steps:
- build template 
- launch debug with Reaper
- add extra plugin to change drawn plugin
- select IPlugTemplate (it's getting bigger every time it's redrawn)

Doesn't happen with iPlug2 examples.

**Comment by olilarkin** [comment] 2024-06-01 17:22
what platform/format?

**Comment by nezvers** [comment] 2024-06-03 10:59
Updated

**Comment by olilarkin** [comment] 2024-06-06 05:19
thanks. I believe this is fixed by applying the changes on this branch https://github.com/iPlug2/iPlug2/tree/VST3/screen-scaled to the iPlug2 submodule

the issue is tracked here: https://github.com/iPlug2/iPlug2/issues/740 , so i will close this issue since it is an iPlug2 issue not iPlug2OOS

**Closed by olilarkin** 2024-06-06 05:19 UTC
